server:
  port: 8008
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/wualtervera/config-server
          search-paths:
            - config-microservices
  application:
    name: config-server