server:
  port: 8009
spring:
  cloud:
    config:
      server:
        git:
          default-label: 

spring.application.name = transaction
spring.data.mongodb.uri=mongodb://localhost:27017/bootcamp